class _BotCommands:
    def __init__(self):
        self.LeechSetCommand = 'leechset'
        self.SetThumbCommand = 'setthumb'
        self.LeechCommand = 'leech'
        self.TarLeechCommand = 'tarleech'
        self.UnzipLeechCommand = 'unzipleech'
        self.ZipLeechCommand = 'zipleech'
        self.QbLeechCommand = 'qbleech'
        self.QbTarLeechCommand = 'qbtarleech'
        self.QbUnzipLeechCommand = 'qbunzipleech'
        self.QbZipLeechCommand = 'qbzipleech'
        self.LeechWatchCommand = 'leechwatch'
        self.LeechTarWatchCommand = 'leechtarwatch'
        self.LeechZipWatchCommand = 'leechzipwatch'
        self.CancelMirror = 'cancel'
        self.CancelAllCommand = 'cancelall'
        self.PingCommand = 'ping'
        self.RestartCommand = 'restart'
        self.StatsCommand = 'stats'
        self.HelpCommand = 'help'
        self.LogCommand = 'log'
        self.SpeedCommand = 'speedtest'
        self.StatusCommand = 'status'

BotCommands = _BotCommands()
