class _BotCommands:
    def __init__(self):
        self.LeechSetCommand = 'leechset'
        self.SetThumbCommand = 'setthumb'
        self.LeechCommand = 'leech'
        self.UnzipLeechCommand = 'unzipleech'
        self.ZipLeechCommand = 'zipleech'
        self.QbLeechCommand = 'qbleech'
        self.QbUnzipLeechCommand = 'qbunzipleech'
        self.QbZipLeechCommand = 'qbzipleech'
        self.LeechWatchCommand = 'ytdl'
        self.LeechZipWatchCommand = 'ytdlzip'
        self.CancelMirror = 'cancel'
        self.CancelAllCommand = 'cancelall'
        self.PingCommand = 'ping'
        self.RestartCommand = 'restart'
        self.StatsCommand = 'stats'
        self.HelpCommand = 'help'
        self.ShellCommand = 'shell'
        self.ExecHelpCommand = 'exechelp'
        self.LogCommand = 'log'
        self.SpeedCommand = 'speedtest'
        self.StatusCommand = 'status'
        self.AuthorizedUsersCommand = 'users'
        self.AuthorizeCommand = 'authorize'
        self.UnAuthorizeCommand = 'unauthorize'
        self.AddSudoCommand = 'addsudo'
        self.RmSudoCommand = 'rmsudo'
        self.YtdlbCommand = 'ytdlb'
        self.YtdlbzCommand = 'ytdlbz'

BotCommands = _BotCommands()
